# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 970)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Decode = QtWidgets.QPushButton(self.tab)
        self.Decode.setObjectName("Decode")
        self.gridLayout_2.addWidget(self.Decode, 2, 0, 1, 1)
        self.Q3 = PlotWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q3.sizePolicy().hasHeightForWidth())
        self.Q3.setSizePolicy(sizePolicy)
        self.Q3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Q3.setObjectName("Q3")
        self.gridLayout_2.addWidget(self.Q3, 1, 0, 1, 1)
        self.Q1 = PlotWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q1.sizePolicy().hasHeightForWidth())
        self.Q1.setSizePolicy(sizePolicy)
        self.Q1.setMidLineWidth(0)
        self.Q1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Q1.setInteractive(True)
        self.Q1.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.Q1.setObjectName("Q1")
        self.gridLayout_2.addWidget(self.Q1, 0, 0, 1, 1)
        self.Q2 = PlotWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q2.sizePolicy().hasHeightForWidth())
        self.Q2.setSizePolicy(sizePolicy)
        self.Q2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Q2.setInteractive(True)
        self.Q2.setObjectName("Q2")
        self.gridLayout_2.addWidget(self.Q2, 0, 1, 1, 1)
        self.Q4 = PlotWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q4.sizePolicy().hasHeightForWidth())
        self.Q4.setSizePolicy(sizePolicy)
        self.Q4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Q4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Q4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Q4.setAlignment(QtCore.Qt.AlignCenter)
        self.Q4.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.Q4.setObjectName("Q4")
        self.gridLayout_2.addWidget(self.Q4, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Q5 = PlotWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q5.sizePolicy().hasHeightForWidth())
        self.Q5.setSizePolicy(sizePolicy)
        self.Q5.setInteractive(True)
        self.Q5.setObjectName("Q5")
        self.gridLayout_3.addWidget(self.Q5, 0, 0, 1, 1)
        self.Q6 = PlotWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q6.sizePolicy().hasHeightForWidth())
        self.Q6.setSizePolicy(sizePolicy)
        self.Q6.setInteractive(True)
        self.Q6.setObjectName("Q6")
        self.gridLayout_3.addWidget(self.Q6, 0, 1, 1, 1)
        self.Q7 = PlotWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q7.sizePolicy().hasHeightForWidth())
        self.Q7.setSizePolicy(sizePolicy)
        self.Q7.setObjectName("Q7")
        self.gridLayout_3.addWidget(self.Q7, 1, 0, 1, 1)
        self.Q8 = PlotWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q8.sizePolicy().hasHeightForWidth())
        self.Q8.setSizePolicy(sizePolicy)
        self.Q8.setObjectName("Q8")
        self.gridLayout_3.addWidget(self.Q8, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Decode.setText(_translate("MainWindow", "Decode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Frist4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Second4"))
from pyqtgraph import PlotWidget
